name: TODO Item
description: For the dev team to keep track of what we need to do
labels: ["todo"]
title: "[TODO] "
body:
  - type: textarea
    id: problem
    attributes:
      label: Related problem
      description: Is your TODO item related to a problem? If so, describe it.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: How is it being implemented?
    validations:
      required: true
