MSBT_TAGS_BY_ID = {
    "0_0": {
        "name": "ruby",
        "description": "ruby annotation rendered above the normal text",
        "group": 0,
        "type": 0,
        "arguments": [
            {
                "name": "byteSpan",
                "description": "number of subsequent characters (as bytes) to render the annotation above (centered)",
                "dataType": "u16",
            },
            {"name": "value", "description": "the annotation text", "dataType": "str"},
        ],
    },
    "0_1": {
        "name": "font",
        "group": 0,
        "type": 1,
        "arguments": [
            {
                "name": "face",
                "dataType": "s16",
                "valueMap": {
                    -1: "Default",
                    0: "Ancient",
                    1: "Thin",
                    2: "ThinOutlined",
                    3: "Unknown",
                    4: "Normal",
                    5: "NormalOutlined",
                    6: "Bold",
                    7: "TitleDeco",
                    8: "Title",
                },
            }
        ],
    },
    "0_2": {
        "name": "size",
        "description": "changes the current text size",
        "group": 0,
        "type": 2,
        "arguments": [
            {"name": "value", "description": "relative text size in percent", "dataType": "u16"}
        ],
    },
    "0_3": {
        "name": "color",
        "description": "changes the current text color",
        "group": 0,
        "type": 3,
        "arguments": [{"name": "id", "description": "id of the color", "dataType": "s16"}],
    },
    "0_4": {"name": "pageBreak", "description": "forces a new dialog page", "group": 0, "type": 4},
    "1_0": {
        "name": "delay",
        "description": "delays the text rendering by a given number of frames",
        "group": 1,
        "type": 0,
        "arguments": [
            {"name": "frames", "description": "number of frames to delay", "dataType": "u16"}
        ],
    },
    "1_3": {
        "name": "playSound",
        "description": "plays a sound",
        "group": 1,
        "type": 3,
        "arguments": [{"name": "id", "description": "id of the sound", "dataType": "u16"}],
    },
    "1_4": {
        "name": "icon",
        "description": "renders an icon",
        "group": 1,
        "type": 4,
        "arguments": [
            {
                "name": "type",
                "description": "icon type",
                "dataType": "u8",
                "valueMap": {
                    0: "LStickUp",
                    1: "LStickDown",
                    2: "LStickLeft",
                    3: "LStickRight",
                    4: "RStickUpDown",
                    5: "RStickRightLeft",
                    6: "DPadUp",
                    7: "DPadDown",
                    8: "DPadLeft",
                    9: "DPadRight",
                    10: "AButton0",
                    11: "AButton1",
                    12: "JumpButton0",
                    13: "YButton",
                    14: "ZLTrigger0",
                    15: "ZLTrigger1",
                    16: "SprintButton0",
                    17: "SprintButton1",
                    18: "SprintButton2",
                    19: "SprintButton3",
                    20: "SprintButton4",
                    21: "RBumper0",
                    22: "LBumper",
                    23: "PlusButton",
                    24: "MinusButton",
                    25: "RightArrow",
                    26: "LeftArrow",
                    27: "UpArrow",
                    28: "DownArrow",
                    29: "UpRightArrow",
                    30: "UpLeftArrow",
                    31: "DownLeftArrow",
                    32: "DownRightArrow",
                    33: "LStick",
                    34: "RStick",
                    35: "LStickLeftRight",
                    36: "NintendoSwitch",
                    37: "JumpButton1",
                    38: "XButton2",
                    39: "BButton",
                    40: "XButton1",
                    41: "PristineWeaponSparkle",
                    42: "RBumper1",
                    43: "DPadUpDown",
                    44: "RoyalCrest",
                },
            }
        ],
    },
    "2_1": {
        "name": "string1",
        "group": 2,
        "type": 1,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "2_2": {
        "name": "number2",
        "group": 2,
        "type": 2,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "2_3": {
        "name": "currentHorseName",
        "description": "gets the name of the current horse",
        "group": 2,
        "type": 3,
    },
    "2_4": {
        "name": "selectedHorseName",
        "description": "gets the name of the currently selected horse",
        "group": 2,
        "type": 4,
    },
    "2_7": {"name": "cookingAdjective", "group": 2, "type": 7},
    "2_8": {"name": "cookingEffectCaption", "group": 2, "type": 8},
    "2_9": {
        "name": "number9",
        "group": 2,
        "type": 9,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "2_11": {
        "name": "string11",
        "group": 2,
        "type": 11,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "2_12": {
        "name": "string12",
        "group": 2,
        "type": 12,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "2_14": {
        "name": "number14",
        "group": 2,
        "type": 14,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "2_15": {
        "name": "number15",
        "group": 2,
        "type": 15,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "2_16": {
        "name": "number16",
        "group": 2,
        "type": 16,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
            {"name": "useDelimiter", "dataType": "bool"},
        ],
    },
    "2_18": {
        "name": "number18",
        "group": 2,
        "type": 18,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "2_19": {
        "name": "number19",
        "group": 2,
        "type": 19,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "2_20": {
        "name": "number20",
        "group": 2,
        "type": 20,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "2_21": {
        "name": "number21",
        "group": 2,
        "type": 21,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "2_22": {
        "name": "number22",
        "group": 2,
        "type": 22,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "2_24": {"name": "attachmentAdjective", "group": 2, "type": 24},
    "2_25": {"name": "equipmentBaseName", "group": 2, "type": 25},
    "2_26": {"name": "essenceAdjective", "group": 2, "type": 26},
    "2_27": {"name": "essenceBaseName", "group": 2, "type": 27},
    "2_28": {"name": "weaponName", "group": 2, "type": 28},
    "2_29": {"name": "playerName", "group": 2, "type": 29},
    "2_30": {"name": "questItemName", "group": 2, "type": 30},
    "2_31": {
        "name": "string31",
        "group": 2,
        "type": 31,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "2_32": {
        "name": "string32",
        "group": 2,
        "type": 32,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "2_33": {
        "name": "string33",
        "group": 2,
        "type": 33,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "2_35": {
        "name": "yonaDynamicName",
        "description": 'dynamic name for the NPC Yona; replaced with "???" if the user has not yet encountered the NPC',
        "group": 2,
        "type": 35,
    },
    "2_36": {
        "name": "string36",
        "group": 2,
        "type": 36,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "2_37": {
        "name": "recipeName",
        "description": "gets the name of the cooking recipe",
        "group": 2,
        "type": 37,
    },
    "3_0": {
        "name": "setEmotion",
        "group": 3,
        "type": 0,
        "arguments": [
            {
                "name": "emotion",
                "dataType": "u8",
                "valueMap": {
                    0: "Normal_Face",
                    1: "Pleasure_Face",
                    2: "Anger_Face",
                    3: "Sorrow_Face",
                    4: "Surprise_Face",
                    5: "Thinking_Face",
                    6: "Serious_Face",
                    7: "Normal",
                    8: "Pleasure",
                    9: "Angry",
                    10: "Sorrow",
                    11: "Surprise",
                    12: "Thinking",
                    13: "Serious",
                },
            },
            {"name": "noVoice", "dataType": "bool"},
        ],
    },
    "3_1": {"name": "setItalicFont", "group": 3, "type": 1},
    "4_0": {
        "name": "setVoice",
        "group": 4,
        "type": 0,
        "arguments": [{"name": "asset", "dataType": "str"}],
    },
    "5_0": {
        "name": "delay8",
        "description": "delays the text rendering by 8 frames",
        "group": 5,
        "type": 0,
    },
    "5_1": {
        "name": "delay15",
        "description": "delays the text rendering by 15 frames",
        "group": 5,
        "type": 1,
    },
    "5_2": {
        "name": "delay30",
        "description": "delays the text rendering by 30 frames",
        "group": 5,
        "type": 2,
    },
    "7_0": {
        "name": "extendVerticalSpace",
        "description": "extends the vertical render space to allow accents on capital letters",
        "group": 7,
        "type": 0,
    },
    "15_0": {
        "name": "resetFontStyle",
        "description": "resets any current font style back to dialog defaults",
        "group": 15,
        "type": 0,
    },
    "201_0": {
        "name": "wordInfo",
        "description": "contains grammatical information about a word",
        "group": 201,
        "type": 0,
        "arguments": [
            {"name": "gender", "description": "id of the gender", "dataType": "u8"},
            {
                "name": "defArticle",
                "description": "id of the definite article (DefArt_<id> in StaticMsg/GrammarArticle)",
                "dataType": "u8",
            },
            {
                "name": "indefArticle",
                "description": "id of the indefinite article (IndefArt_<id> in StaticMsg/GrammarArticle)",
                "dataType": "u8",
            },
            {
                "name": "isPlural",
                "description": "whether the word is in plural",
                "dataType": "bool",
            },
        ],
    },
    "201_1": {
        "name": "defArticle",
        "description": "definite article from StaticMsg/GrammarArticle determined by a wordInfo function",
        "group": 201,
        "type": 1,
    },
    "201_2": {
        "name": "indefArticle",
        "description": "indefinite article from StaticMsg/GrammarArticle determined by a wordInfo function",
        "group": 201,
        "type": 2,
    },
    "201_3": {
        "name": "uppercaseNextWord",
        "description": "transforms the first letter of the next word to uppercase",
        "group": 201,
        "type": 3,
    },
    "201_4": {
        "name": "lowercaseNextWord",
        "description": "transforms the first letter of the next word to lowercase",
        "group": 201,
        "type": 4,
    },
    "201_5": {
        "name": "gender",
        "description": "contains gender-specific strings; decision on which string to select is determined by a wordInfo function",
        "group": 201,
        "type": 5,
        "arguments": [
            {"name": "m", "description": "masculine value", "dataType": "str"},
            {"name": "f", "description": "feminine value", "dataType": "str"},
            {"name": "n", "description": "neuter value", "dataType": "str"},
        ],
    },
    "201_6": {
        "name": "pluralCase",
        "group": 201,
        "type": 6,
        "arguments": [
            {
                "name": "arg1",
                "dataType": "str",
                "description": "EUfr/USfr: 0 or 1 item\nEUru: numbers ending in 1, but not 11\nOther languages: 1 item",
            },
            {
                "name": "arg2",
                "dataType": "str",
                "description": "EUfr/USfr: 2 or more items\nEUru: numbers ending in 2,3,4, but not 12,13,14\nOther languages: 0, 2, or more items",
            },
            {
                "name": "arg3",
                "dataType": "str",
                "description": "EUru: numbers ending in 5,6,7,8,9,0, and 11,12,13,14\nUnused in other languages",
            },
        ],
    },
    "201_7": {
        "name": "batchimObject",
        "group": 201,
        "type": 7,
        "description": "korean support consonant in a syllable, specifically if referring to an object",
        "arguments": [
            {
                "name": "consonant",
                "dataType": "str",
                "description": "the value to insert if the syllable block ends with a consonant",
            },
            {
                "name": "vowel",
                "dataType": "str",
                "description": "the value to insert if the syllable block ends with a vowel",
            },
        ],
    },
    "201_8": {
        "name": "batchimDirection",
        "group": 201,
        "type": 8,
        "description": "korean support consonant in a syllable, specifically if referring to a direction",
        "arguments": [
            {
                "name": "consonant",
                "dataType": "str",
                "description": "the value to insert if the syllable block ends with a consonant",
            },
            {
                "name": "vowel",
                "dataType": "str",
                "description": "the value to insert if the syllable block ends with a vowel",
            },
        ],
    },
    "201_9": {
        "name": "nounCase",
        "group": 201,
        "type": 9,
        "arguments": [{"name": "type", "dataType": "u8"}],
    },
    "201_10": {
        "name": "gender10",
        "group": 201,
        "type": 10,
        "arguments": [
            {"name": "arg1", "dataType": "str"},
            {"name": "arg2", "dataType": "str"},
            {"name": "arg3", "dataType": "str"},
            {"name": "arg4", "dataType": "str"},
            {"name": "arg5", "dataType": "str"},
            {"name": "arg6", "dataType": "str"},
            {"name": "arg7", "dataType": "str"},
            {"name": "arg8", "dataType": "str"},
            {"name": "arg9", "dataType": "str"},
            {"name": "arg10", "dataType": "str"},
            {"name": "arg11", "dataType": "str"},
            {"name": "arg12", "dataType": "str"},
        ],
    },
}
MSBT_TAGS_BY_NAME = {
    "ruby": {
        "name": "ruby",
        "description": "ruby annotation rendered above the normal text",
        "group": 0,
        "type": 0,
        "arguments": [
            {
                "name": "byteSpan",
                "description": "number of subsequent characters (as bytes) to render the annotation above (centered)",
                "dataType": "u16",
            },
            {"name": "value", "description": "the annotation text", "dataType": "str"},
        ],
    },
    "font": {
        "name": "font",
        "group": 0,
        "type": 1,
        "arguments": [
            {
                "name": "face",
                "dataType": "s16",
                "valueMap": {
                    -1: "Default",
                    0: "Ancient",
                    1: "Thin",
                    2: "ThinOutlined",
                    3: "Unknown",
                    4: "Normal",
                    5: "NormalOutlined",
                    6: "Bold",
                    7: "TitleDeco",
                    8: "Title",
                },
            }
        ],
    },
    "size": {
        "name": "size",
        "description": "changes the current text size",
        "group": 0,
        "type": 2,
        "arguments": [
            {"name": "value", "description": "relative text size in percent", "dataType": "u16"}
        ],
    },
    "color": {
        "name": "color",
        "description": "changes the current text color",
        "group": 0,
        "type": 3,
        "arguments": [{"name": "id", "description": "id of the color", "dataType": "s16"}],
    },
    "pageBreak": {
        "name": "pageBreak",
        "description": "forces a new dialog page",
        "group": 0,
        "type": 4,
    },
    "delay": {
        "name": "delay",
        "description": "delays the text rendering by a given number of frames",
        "group": 1,
        "type": 0,
        "arguments": [
            {"name": "frames", "description": "number of frames to delay", "dataType": "u16"}
        ],
    },
    "playSound": {
        "name": "playSound",
        "description": "plays a sound",
        "group": 1,
        "type": 3,
        "arguments": [{"name": "id", "description": "id of the sound", "dataType": "u16"}],
    },
    "icon": {
        "name": "icon",
        "description": "renders an icon",
        "group": 1,
        "type": 4,
        "arguments": [
            {
                "name": "type",
                "description": "icon type",
                "dataType": "u8",
                "valueMap": {
                    0: "LStickUp",
                    1: "LStickDown",
                    2: "LStickLeft",
                    3: "LStickRight",
                    4: "RStickUpDown",
                    5: "RStickRightLeft",
                    6: "DPadUp",
                    7: "DPadDown",
                    8: "DPadLeft",
                    9: "DPadRight",
                    10: "AButton0",
                    11: "AButton1",
                    12: "JumpButton0",
                    13: "YButton",
                    14: "ZLTrigger0",
                    15: "ZLTrigger1",
                    16: "SprintButton0",
                    17: "SprintButton1",
                    18: "SprintButton2",
                    19: "SprintButton3",
                    20: "SprintButton4",
                    21: "RBumper0",
                    22: "LBumper",
                    23: "PlusButton",
                    24: "MinusButton",
                    25: "RightArrow",
                    26: "LeftArrow",
                    27: "UpArrow",
                    28: "DownArrow",
                    29: "UpRightArrow",
                    30: "UpLeftArrow",
                    31: "DownLeftArrow",
                    32: "DownRightArrow",
                    33: "LStick",
                    34: "RStick",
                    35: "LStickLeftRight",
                    36: "NintendoSwitch",
                    37: "JumpButton1",
                    38: "XButton2",
                    39: "BButton",
                    40: "XButton1",
                    41: "PristineWeaponSparkle",
                    42: "RBumper1",
                    43: "DPadUpDown",
                    44: "RoyalCrest",
                },
            }
        ],
    },
    "string1": {
        "name": "string1",
        "group": 2,
        "type": 1,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "number2": {
        "name": "number2",
        "group": 2,
        "type": 2,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "currentHorseName": {
        "name": "currentHorseName",
        "description": "gets the name of the current horse",
        "group": 2,
        "type": 3,
    },
    "selectedHorseName": {
        "name": "selectedHorseName",
        "description": "gets the name of the currently selected horse",
        "group": 2,
        "type": 4,
    },
    "cookingAdjective": {"name": "cookingAdjective", "group": 2, "type": 7},
    "cookingEffectCaption": {"name": "cookingEffectCaption", "group": 2, "type": 8},
    "number9": {
        "name": "number9",
        "group": 2,
        "type": 9,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "string11": {
        "name": "string11",
        "group": 2,
        "type": 11,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "string12": {
        "name": "string12",
        "group": 2,
        "type": 12,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "number14": {
        "name": "number14",
        "group": 2,
        "type": 14,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "number15": {
        "name": "number15",
        "group": 2,
        "type": 15,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "number16": {
        "name": "number16",
        "group": 2,
        "type": 16,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
            {"name": "useDelimiter", "dataType": "bool"},
        ],
    },
    "number18": {
        "name": "number18",
        "group": 2,
        "type": 18,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "number19": {
        "name": "number19",
        "group": 2,
        "type": 19,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "number20": {
        "name": "number20",
        "group": 2,
        "type": 20,
        "arguments": [
            {"name": "ref", "dataType": "str"},
            {"name": "index", "dataType": "s16"},
            {"name": "isDirect", "dataType": "bool"},
        ],
    },
    "number21": {
        "name": "number21",
        "group": 2,
        "type": 21,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "number22": {
        "name": "number22",
        "group": 2,
        "type": 22,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "attachmentAdjective": {"name": "attachmentAdjective", "group": 2, "type": 24},
    "equipmentBaseName": {"name": "equipmentBaseName", "group": 2, "type": 25},
    "essenceAdjective": {"name": "essenceAdjective", "group": 2, "type": 26},
    "essenceBaseName": {"name": "essenceBaseName", "group": 2, "type": 27},
    "weaponName": {"name": "weaponName", "group": 2, "type": 28},
    "playerName": {"name": "playerName", "group": 2, "type": 29},
    "questItemName": {"name": "questItemName", "group": 2, "type": 30},
    "string31": {
        "name": "string31",
        "group": 2,
        "type": 31,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "string32": {
        "name": "string32",
        "group": 2,
        "type": 32,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "string33": {
        "name": "string33",
        "group": 2,
        "type": 33,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "yonaDynamicName": {
        "name": "yonaDynamicName",
        "description": 'dynamic name for the NPC Yona; replaced with "???" if the user has not yet encountered the NPC',
        "group": 2,
        "type": 35,
    },
    "string36": {
        "name": "string36",
        "group": 2,
        "type": 36,
        "arguments": [{"name": "ref", "dataType": "str"}, {"name": "index", "dataType": "s16"}],
    },
    "recipeName": {
        "name": "recipeName",
        "description": "gets the name of the cooking recipe",
        "group": 2,
        "type": 37,
    },
    "setEmotion": {
        "name": "setEmotion",
        "group": 3,
        "type": 0,
        "arguments": [
            {
                "name": "emotion",
                "dataType": "u8",
                "valueMap": {
                    0: "Normal_Face",
                    1: "Pleasure_Face",
                    2: "Anger_Face",
                    3: "Sorrow_Face",
                    4: "Surprise_Face",
                    5: "Thinking_Face",
                    6: "Serious_Face",
                    7: "Normal",
                    8: "Pleasure",
                    9: "Angry",
                    10: "Sorrow",
                    11: "Surprise",
                    12: "Thinking",
                    13: "Serious",
                },
            },
            {"name": "noVoice", "dataType": "bool"},
        ],
    },
    "setItalicFont": {"name": "setItalicFont", "group": 3, "type": 1},
    "setVoice": {
        "name": "setVoice",
        "group": 4,
        "type": 0,
        "arguments": [{"name": "asset", "dataType": "str"}],
    },
    "delay8": {
        "name": "delay8",
        "description": "delays the text rendering by 8 frames",
        "group": 5,
        "type": 0,
    },
    "delay15": {
        "name": "delay15",
        "description": "delays the text rendering by 15 frames",
        "group": 5,
        "type": 1,
    },
    "delay30": {
        "name": "delay30",
        "description": "delays the text rendering by 30 frames",
        "group": 5,
        "type": 2,
    },
    "extendVerticalSpace": {
        "name": "extendVerticalSpace",
        "description": "extends the vertical render space to allow accents on capital letters",
        "group": 7,
        "type": 0,
    },
    "resetFontStyle": {
        "name": "resetFontStyle",
        "description": "resets any current font style back to dialog defaults",
        "group": 15,
        "type": 0,
    },
    "wordInfo": {
        "name": "wordInfo",
        "description": "contains grammatical information about a word",
        "group": 201,
        "type": 0,
        "arguments": [
            {"name": "gender", "description": "id of the gender", "dataType": "u8"},
            {
                "name": "defArticle",
                "description": "id of the definite article (DefArt_<id> in StaticMsg/GrammarArticle)",
                "dataType": "u8",
            },
            {
                "name": "indefArticle",
                "description": "id of the indefinite article (IndefArt_<id> in StaticMsg/GrammarArticle)",
                "dataType": "u8",
            },
            {
                "name": "isPlural",
                "description": "whether the word is in plural",
                "dataType": "bool",
            },
        ],
    },
    "defArticle": {
        "name": "defArticle",
        "description": "definite article from StaticMsg/GrammarArticle determined by a wordInfo function",
        "group": 201,
        "type": 1,
    },
    "indefArticle": {
        "name": "indefArticle",
        "description": "indefinite article from StaticMsg/GrammarArticle determined by a wordInfo function",
        "group": 201,
        "type": 2,
    },
    "uppercaseNextWord": {
        "name": "uppercaseNextWord",
        "description": "transforms the first letter of the next word to uppercase",
        "group": 201,
        "type": 3,
    },
    "lowercaseNextWord": {
        "name": "lowercaseNextWord",
        "description": "transforms the first letter of the next word to lowercase",
        "group": 201,
        "type": 4,
    },
    "gender": {
        "name": "gender",
        "description": "contains gender-specific strings; decision on which string to select is determined by a wordInfo function",
        "group": 201,
        "type": 5,
        "arguments": [
            {"name": "m", "description": "masculine value", "dataType": "str"},
            {"name": "f", "description": "feminine value", "dataType": "str"},
            {"name": "n", "description": "neuter value", "dataType": "str"},
        ],
    },
    "pluralCase": {
        "name": "pluralCase",
        "group": 201,
        "type": 6,
        "arguments": [
            {
                "name": "arg1",
                "dataType": "str",
                "description": "EUfr/USfr: 0 or 1 item\nEUru: numbers ending in 1, but not 11\nOther languages: 1 item",
            },
            {
                "name": "arg2",
                "dataType": "str",
                "description": "EUfr/USfr: 2 or more items\nEUru: numbers ending in 2,3,4, but not 12,13,14\nOther languages: 0, 2, or more items",
            },
            {
                "name": "arg3",
                "dataType": "str",
                "description": "EUru: numbers ending in 5,6,7,8,9,0, and 11,12,13,14\nUnused in other languages",
            },
        ],
    },
    "batchimObject": {
        "name": "batchimObject",
        "group": 201,
        "type": 7,
        "description": "korean support consonant in a syllable, specifically if referring to an object",
        "arguments": [
            {
                "name": "consonant",
                "dataType": "str",
                "description": "the value to insert if the syllable block ends with a consonant",
            },
            {
                "name": "vowel",
                "dataType": "str",
                "description": "the value to insert if the syllable block ends with a vowel",
            },
        ],
    },
    "batchimDirection": {
        "name": "batchimDirection",
        "group": 201,
        "type": 8,
        "description": "korean support consonant in a syllable, specifically if referring to a direction",
        "arguments": [
            {
                "name": "consonant",
                "dataType": "str",
                "description": "the value to insert if the syllable block ends with a consonant",
            },
            {
                "name": "vowel",
                "dataType": "str",
                "description": "the value to insert if the syllable block ends with a vowel",
            },
        ],
    },
    "nounCase": {
        "name": "nounCase",
        "group": 201,
        "type": 9,
        "arguments": [{"name": "type", "dataType": "u8"}],
    },
    "gender10": {
        "name": "gender10",
        "group": 201,
        "type": 10,
        "arguments": [
            {"name": "arg1", "dataType": "str"},
            {"name": "arg2", "dataType": "str"},
            {"name": "arg3", "dataType": "str"},
            {"name": "arg4", "dataType": "str"},
            {"name": "arg5", "dataType": "str"},
            {"name": "arg6", "dataType": "str"},
            {"name": "arg7", "dataType": "str"},
            {"name": "arg8", "dataType": "str"},
            {"name": "arg9", "dataType": "str"},
            {"name": "arg10", "dataType": "str"},
            {"name": "arg11", "dataType": "str"},
            {"name": "arg12", "dataType": "str"},
        ],
    },
}
